version: "3"

services:
  server:
    image: malann/yiffer-srv:uploads
    ports:
      - "8012:8012"
    volumes:
      - /etc/yifferconfig/:/config/
    networks:
      - proxy-net
      - cloudsql-net

  server-new:
    image: malann/yiffer-srv-new:dev
    ports:
      - "8018:8018"
    volumes:
      - /etc/yifferconfig/:/config/
    networks:
      - proxy-net
      - cloudsql-net

  client:
    image: malann/yiffer-cli:beta
    ports:
      - "8080:8080"
    networks:
      - proxy-net

  ads-client:
    image: malann/yiffer-ads-cli:5.0.0
    ports:
      - "8081:8081"
    networks:
      - proxy-net

  admin-client:
    image: malann/yiffer-admin-cli:beta
    ports:
      - "8082:8082"
    networks:
      - proxy-net

  reverseproxy:
    image: malann/yiffer-proxy:latest
    volumes:
      - /etc/yifferconfig/nginx.conf:/etc/nginx/nginx.conf
      - /etc/yifferconfig/ssl/:/etc/ssl/
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-net

  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy --dir=/cloudsql -instances=yifferxyz:us-central1:yifferdb=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json
    ports:
      - 5432:5432
    volumes:
      - /etc/yifferconfig/google-cloud-sql-storage-config.json:/secrets/cloudsql/credentials.json
    restart: always
    networks:
      - cloudsql-net

networks:
  proxy-net:
    external: false
  cloudsql-net:
