version: "3"

services:
  server:
    image: malann/yiffer-srv:latest
    ports:
      - "8012:8012"
    volumes:
      - /etc/yifferconfig/:/config/
    networks:
      - proxy-net

  client:
    image: malann/yiffer-cli:latest
    ports:
      - "8080:8080"
    networks:
      - proxy-net

  ads-client:
    image: malann/yiffer-ads-cli:latest
    ports:
      - "8081:8081"
    networks:
      - proxy-net

  admin-client:
    image: malann/yiffer-admin-cli:latest
    ports:
      - "8082:8082"
    networks:
      - proxy-net

  reverseproxy:
    image: malann/yiffer-proxy:latest
    volumes:
      - /etc/yifferconfig/nginx.conf:/etc/nginx/nginx.conf
      - /etc/yifferconfig/ssl/:/etc/ssl/
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy-net

networks:
  proxy-net:
    external: false

